services:
  db:
    image: mysql:latest  # Använd MySQL senaste version
    environment:
      MYSQL_ROOT_PASSWORD: password  # Ange root-lösenord
      MYSQL_DATABASE: Labb1  # Skapa en databas vid start
      MYSQL_USER: user  # Skapa en användare
      MYSQL_PASSWORD: userpassword  # Ange lösenord för användaren
    volumes:
      - dbdata:/var/lib/mysql  # Persistent lagring för MySQL-data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Init directory för SQL-skript
    ports:
      - "3306:3306"  # Exponera MySQL på port 3306

volumes:
  dbdata:
    driver: local  # Använd standard lokal volymdrivrutin
